site_name: Wiki Docs of Han

theme:
  name: 'material'

nav:
    - Home: index.md
    - ASM: ASM.md
    - clusterProfile: clusterProfiler.md
    - CpG island: CpG_island_classification.md
    - Methylation haolo: methy_Haplo.md
    - PMD: PMD.md
    - BETA: BETA.md